### ISSUE TITLE
How to check participants code auomatically

### ISSUE THREAD

**Issue by at15** [dyweb/todoBoard#1]
It would be dumb to check everyone's code using bare eye instead of automatic tests

But there are some issues 
- should we could create separated repos for front end, backend? If put them all together, it would be hard to run test and coverage etc.
- participants fork the original repos, but they will only know if they pass the test in travis after they create a pr.
- if we let participants create their own repo, they won't be able to get the updated tests we wrote.

I will have a try first

**Comment by at15** [comment]
for browser test http://karma-runner.github.io/0.13/index.html

**Comment by arrowrowe** [comment]
- Store user name in `./.env.json`.
- Test only `./participants/{username}` locally. Tests all if `./.env.json` not found.
- Store task ID in `./participants/{username}/.task.json` to specify which tests to run.
- Participants run tests locally before open a PR.

**Comment by at15** [comment]
well, I guess it's time to consider it again

**Comment by at15** [comment]
well, I guess it's time to archive the repo cc @ComMouse

**Comment by at15** [comment]
close due to age
